const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCEEDED: 'USERS_LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'USERS_LOGIN_FAILED',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCEEDED: 'USERS_REGISTER_SUCCEEDED',
  REGISTER_FAILED: 'USERS_REGISTER_FAILED',

  LOGOUT: 'USERS_LOGOUT',
};

export default userConstants;
